/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cuenta.vistas;

import cuenta.Articulo;
import cuenta.Cliente;
import cuenta.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author lio
 */
public class ViewTienda extends javax.swing.JFrame {

    /**
     * Creates new form ViewTienda
     */
    
    Cuenta cuenta = new Cuenta("", 0, 0);
    Articulo articulo = new Articulo(0, "", 0);
    
    public ViewTienda() {
        initComponents();
    }

    public ViewTienda(Articulo articulo , Cuenta cuenta){
        initComponents();
        this.articulo = articulo;
        this.cuenta = cuenta;
    }
    
    public String showNombre( Cliente cliente ){
        String nombre = cliente.nombre;
        showNombre.setText(nombre);
        return nombre;
    }
    
    public double showLimiteYSaldo( Cuenta cuenta ){
       double limite = cuenta.limite;
       double saldo = cuenta.saldo;
       showLimite.setText(String.valueOf(limite));
       showSaldo.setText(String.valueOf(saldo));
       return saldo; 
    }
    
    public String showArticulos( Articulo articulo ){
       String nombre = articulo.nombre;
       double precio = articulo.precio;
       showArticulo.setText(nombre);
       showPrecio.setText(String.valueOf(precio));
       return nombre;
    }
    
    public double Comprar( Cuenta cuenta , Articulo articulo){
        double saldoAnterior;
        double saldo;
        
        saldoAnterior = cuenta.saldo;
        saldo = saldoAnterior + articulo.precio;
        if( saldo > cuenta.limite ){
            JOptionPane.showMessageDialog(this, "límite de crédito Excedido");
            showSaldo.setText("LIMITE EXCEDIDO");
            buttonComprar.setEnabled(false);
        }else{
            cuenta.saldo = saldo;
            showLimiteYSaldo(cuenta);
        }
        return saldo;
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textInfo = new javax.swing.JLabel();
        textInfo2 = new javax.swing.JLabel();
        showArticulo = new javax.swing.JLabel();
        textInfo3 = new javax.swing.JLabel();
        showPrecio = new javax.swing.JLabel();
        textInfoSaldo = new javax.swing.JLabel();
        textInfoLimite = new javax.swing.JLabel();
        showSaldo = new javax.swing.JLabel();
        showLimite = new javax.swing.JLabel();
        buttonComprar = new javax.swing.JButton();
        showNombre = new javax.swing.JLabel();
        textInfoPesos = new javax.swing.JLabel();
        textInfoPesos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras en Linea");

        textInfo.setText("Bienvenido a la Tienda de Fayuca");

        textInfo2.setText("Articulos Disponibles:");

        showArticulo.setText("jLabel2");

        textInfo3.setText("Precio");

        showPrecio.setText("jLabel1");

        textInfoSaldo.setText("Saldo");

        textInfoLimite.setText("Limite");

        showSaldo.setText("jLabel1");

        showLimite.setText("jLabel1");

        buttonComprar.setText("Comprar");
        buttonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComprarActionPerformed(evt);
            }
        });

        showNombre.setText("jLabel1");

        textInfoPesos.setText("$");

        textInfoPesos1.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textInfo2)
                            .addComponent(showArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textInfoPesos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(showPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textInfo3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textInfoSaldo)
                            .addComponent(showSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textInfoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textInfoLimite))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonComprar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInfo)
                    .addComponent(showNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInfo2)
                    .addComponent(textInfo3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showArticulo)
                    .addComponent(showPrecio)
                    .addComponent(textInfoPesos1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInfoSaldo)
                    .addComponent(textInfoLimite))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showSaldo)
                    .addComponent(showLimite)
                    .addComponent(textInfoPesos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(buttonComprar)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Compras en Tiendita");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprarActionPerformed
        // TODO add your handling code here:
        Comprar(cuenta, articulo);
    }//GEN-LAST:event_buttonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComprar;
    private javax.swing.JLabel showArticulo;
    private javax.swing.JLabel showLimite;
    private javax.swing.JLabel showNombre;
    private javax.swing.JLabel showPrecio;
    private javax.swing.JLabel showSaldo;
    private javax.swing.JLabel textInfo;
    private javax.swing.JLabel textInfo2;
    private javax.swing.JLabel textInfo3;
    private javax.swing.JLabel textInfoLimite;
    private javax.swing.JLabel textInfoPesos;
    private javax.swing.JLabel textInfoPesos1;
    private javax.swing.JLabel textInfoSaldo;
    // End of variables declaration//GEN-END:variables
}
