
import java.awt.Color;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lio
 */
public class VistaResultados extends javax.swing.JFrame {

    /**
     * Creates new form VistaResultados
     */
    public VistaResultados() {
        initComponents();
    }
    
/*    public Geometria setValues(Circulo circulo , Rectangulo rectangulo, Recta recta){
        Circulo circulo1 = new Circulo(circulo);
        Rectangulo rectangulo1 = new Rectangulo(rectangulo.x, rectangulo.y);
        Recta recta1 = new Recta(recta.x1, recta.x2);
        return circulo1;
    }*/
    
    public VistaResultados(double areaCirculo){
        double areaCirculito = areaCirculo;
    }
    
    public Double setAreaCirculo( double areaCirculo ){
        labelResultadoArea.setText(String.valueOf(areaCirculo));
        return areaCirculo;
    }
    
    public Double setPerimetroCirculo( double perimetroCirculo ){
        labelPerimientroCirculoResultado.setText(String.valueOf(perimetroCirculo));
        return perimetroCirculo;
    }
    
    public Double setAreaRectangulo( double areaRectangulo ){
        labelResultadoAreaRectangulo.setText(String.valueOf(areaRectangulo));
        return areaRectangulo;
    }
    
    public Double setPerimetroRectangulo( double perimetroRectangulo ){
        labelResultadoPerimetroRectangulo.setText(String.valueOf(perimetroRectangulo));
        return perimetroRectangulo;
    }
    
    public Double setLongitudRecta( double longitudRecta ){
        labelResultadoLongitud.setText(String.valueOf(longitudRecta));
        return longitudRecta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelResultadoArea = new javax.swing.JLabel();
        labelPerimientroCirculoResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelResultadoAreaRectangulo = new javax.swing.JLabel();
        labelResultadoPerimetroRectangulo = new javax.swing.JLabel();
        labelResultadoLongitud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultados");

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Circulo");

        jLabel2.setText("Area:");

        jLabel3.setText("Perimetro:");

        labelResultadoArea.setForeground(new java.awt.Color(51, 51, 255));
        labelResultadoArea.setText("jLabel4");

        labelPerimientroCirculoResultado.setForeground(new java.awt.Color(51, 51, 255));
        labelPerimientroCirculoResultado.setText("jLabel5");

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Rectangulo");

        jLabel5.setText("Area:");

        jLabel6.setText("Perimetro:");

        jLabel7.setText("Recta");

        jLabel8.setText("Longitud:");

        labelResultadoAreaRectangulo.setForeground(new java.awt.Color(255, 0, 51));
        labelResultadoAreaRectangulo.setText("jLabel9");

        labelResultadoPerimetroRectangulo.setForeground(new java.awt.Color(255, 0, 51));
        labelResultadoPerimetroRectangulo.setText("jLabel9");

        labelResultadoLongitud.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelResultadoAreaRectangulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelResultadoPerimetroRectangulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelResultadoArea))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPerimientroCirculoResultado))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8)
                        .addGap(102, 102, 102)
                        .addComponent(labelResultadoLongitud)))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelResultadoArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelPerimientroCirculoResultado))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelResultadoAreaRectangulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelResultadoPerimetroRectangulo))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelResultadoLongitud))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelPerimientroCirculoResultado;
    private javax.swing.JLabel labelResultadoArea;
    private javax.swing.JLabel labelResultadoAreaRectangulo;
    private javax.swing.JLabel labelResultadoLongitud;
    private javax.swing.JLabel labelResultadoPerimetroRectangulo;
    // End of variables declaration//GEN-END:variables
}
