
import java.awt.Color;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lio
 */
public class VistaDatos extends javax.swing.JFrame {

    /**
     * Creates new form VistaDatos
     */
    public VistaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInstrucciones = new javax.swing.JLabel();
        labelCirculo = new javax.swing.JLabel();
        labelBaseRectangulo = new javax.swing.JLabel();
        labelAlturaRectangulo = new javax.swing.JLabel();
        labelInicioRecta = new javax.swing.JLabel();
        labelFinalRecta = new javax.swing.JLabel();
        textCirculo = new javax.swing.JTextField();
        textBaseRectangulo = new javax.swing.JTextField();
        textAlturaRectangulo = new javax.swing.JTextField();
        textInicioRecta = new javax.swing.JTextField();
        textFinalRecta = new javax.swing.JTextField();
        buttonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelInstrucciones.setText("Introduce las Medidas de las Figuras a Calcular :");

        labelCirculo.setText("Radio del Circulo:");

        labelBaseRectangulo.setText("Base Rectangulo:");

        labelAlturaRectangulo.setText("Altura Rectangulo:");

        labelInicioRecta.setText("Introduce el valor inicial de la Recta:");

        labelFinalRecta.setText("Introduce el valor final de la Recta:");

        textCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCirculoActionPerformed(evt);
            }
        });

        textFinalRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFinalRectaActionPerformed(evt);
            }
        });

        buttonCalcular.setText("Calcular y Dibujar.");
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelInicioRecta)
                                .addComponent(labelFinalRecta))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFinalRecta)
                                .addComponent(textInicioRecta)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelInstrucciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlturaRectangulo)
                                    .addComponent(labelBaseRectangulo)
                                    .addComponent(labelCirculo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCirculo)
                                    .addComponent(textBaseRectangulo)
                                    .addComponent(textAlturaRectangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInstrucciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCirculo)
                    .addComponent(textCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBaseRectangulo)
                    .addComponent(textBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlturaRectangulo)
                    .addComponent(textAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInicioRecta)
                    .addComponent(textInicioRecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFinalRecta)
                    .addComponent(textFinalRecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCirculoActionPerformed

    private void textFinalRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFinalRectaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFinalRectaActionPerformed

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
        // TODO add your handling code here:
        //Declaración de Variables
        double radio;
        double base , altura;
        double inicio, fin;
        
        //Asignacion de valores a las variables
        radio = Double.parseDouble(textCirculo.getText());
        base = Double.parseDouble(textBaseRectangulo.getText());
        altura = Double.parseDouble(textAlturaRectangulo.getText());
        inicio = Double.parseDouble(textInicioRecta.getText());
        fin = Double.parseDouble(textFinalRecta.getText());
        
        //Creación de Objetos ya con valores obtenidos
        Circulo circulo = new Circulo(radio);
        Rectangulo rectangulo = new Rectangulo(base, altura);
        Recta recta = new Recta(inicio, fin);
        VistaResultados vistaResultados = new VistaResultados();

        //Obtención de areas y perimetros
        double areaCirculo = circulo.area();
        double perimetroCirculo = circulo.perimetro();
        double areaRectangulo = rectangulo.area();
        double perimetroRectangulo = rectangulo.perimetro();
        double longitud = recta.perimetro();
        
        //Envio de valores a la vista que nos va a dar la ifnormacion solicitada
        vistaResultados.setAreaCirculo(areaCirculo);
        vistaResultados.setPerimetroCirculo(perimetroCirculo);
        vistaResultados.setAreaRectangulo(areaRectangulo);
        vistaResultados.setPerimetroRectangulo(perimetroRectangulo);
        vistaResultados.setLongitudRecta(longitud);
        vistaResultados.setVisible(true);
    }//GEN-LAST:event_buttonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JLabel labelAlturaRectangulo;
    private javax.swing.JLabel labelBaseRectangulo;
    private javax.swing.JLabel labelCirculo;
    private javax.swing.JLabel labelFinalRecta;
    private javax.swing.JLabel labelInicioRecta;
    private javax.swing.JLabel labelInstrucciones;
    private javax.swing.JTextField textAlturaRectangulo;
    private javax.swing.JTextField textBaseRectangulo;
    private javax.swing.JTextField textCirculo;
    private javax.swing.JTextField textFinalRecta;
    private javax.swing.JTextField textInicioRecta;
    // End of variables declaration//GEN-END:variables
}
